// Generated by https://github.com/dodowhat/china-ip-rules

var ipList = __IPLIST__;

var proxy = "__PROXY__";

var direct = 'DIRECT;';

function FindProxyForURL(url, host) {
    for (var i = 0; i < ipList.length; i++) {
        if (isInNet(host, ipList[i][0], ipList[i][1])) {
            return direct;
        }
    }
    return proxy;
}
